services:
  - type: web
    name: birthday-site          # choose any name you like
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
